#!/bin/bash

function fibin(){
a=0
b=1
c=0
sum=0
	echo $a
	for((i=0;i<$1;i++))
	do
		c=$(($a + $b)) 				
		a=$b
		b=$c
		echo $a
		if [ $(($a % 2)) -eq 0 ]
		then
			sum=$(($sum + $a))			
		fi
	done
echo "This is the sum of even fibonacci numbers:"$sum
}
fibin $1

