#!/bin/bash


function fizzBuzz(){
for ((i=1;i<=$1;i++))
do
	if [ $(($i % 3)) -eq 0 ] && [ $(($i % 5)) -eq 0 ]
	then
		echo "fizzbuzz"
	elif [ $(($i % 3)) -eq 0 ]
	then
		echo "fizz"
	elif [ $(($i % 5)) -eq 0 ]
	then	
		echo "buzz"
	else
		echo "$i"
	fi
done
}
fizzBuzz $1
